### ISSUE TITLE
Cursor not displaying

### ISSUE THREAD

**Issue by approots** [furqanZafar/react-selectize#1]
![react-selectize-missing-cursor](https://cloud.githubusercontent.com/assets/235342/9972847/866577ca-5e1e-11e5-97b8-ec86c5e2d911.png)

Using SimpleSelect, the cursor does not display and I cannot see the text that I type.

**Comment by furqanZafar** [comment]
A bit more information would be helpful, Browser version? Code snippet?

**Comment by approots** [comment]
Thanks. Same problem in all browsers tested - Chrome 45, FF, IE. Using React 0.14.0-rc1. I'm just using a basic example:

    return (
            <div>
                <SimpleSelect
                    placeholder = "Select a fruit"
                    options = {["apple", "mango", "orange", "banana"].map(fruit => {
                        return {label: fruit, value: fruit}
                    })}
                />
            </div>
    )

**Comment by approots** [comment]
Not fixed for me using 0.2.0 and the latest css. I'm not sure how to use autosize or whether that would solve my problem.

**Comment by furqanZafar** [comment]
try using:
```
autosize = {function(search){
 return 100;
}}
```
i am unable to reproduce the issue in all the browsers i tested. if the above doesn't work try setting this https://github.com/furqanZafar/react-selectize/blob/develop/src/ReactSelectize.styl#L42 to `width: 100px !important`

**Comment by approots** [comment]
Thanks, the `width: 100px !important` on the input fixed the issue.

The examples pages have no issues for me.

**Comment by furqanZafar** [comment]
The `autosize` function updates the style attribute of the input control, if the examples work and `width: 100px !important` works then there is likely another css in your page that overrides the style attribute of `input` using `!important`.

**Comment by furqanZafar** [comment]
incorporated fix in release 0.2.2.
