### ISSUE TITLE
Uncaught TypeError: p is not a function

### ISSUE THREAD

**Issue by xxRockOnxx** [furqanZafar/react-selectize#105]
Just followed the docs and copied the sample.

Chrome's console is pointing at this line (1799 when prettified): 

case !(!this.props.hasOwnProperty(e) && this.props.hasOwnProperty(p("on-" + e + "-change"))):

**Comment by baopham** [comment]
Are you using bower version? From debugging, the `p` here is the function `camelize` from prelude-ls. The bower version for prelude-ls is outdated it seems.

**Comment by xxRockOnxx** [comment]
Not using `react` anymore and it's been almost a year and I already forgot the issue.
