### ISSUE TITLE
React.findDOMNode is deprecated

### ISSUE THREAD

**Issue by jamesjjk** [furqanZafar/react-selectize#11]
Hi @furqanZafar,

Using React 0.14 with current revision "version": "0.2.6",

Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

**Comment by furqanZafar** [comment]
upgrade to the latest version `0.3.6` it works with 0.14

**Comment by jamesjjk** [comment]
@furqanZafar done, however now I get a Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by jamesjjk** [comment]
@furqanZafar Apologies the package did not overwrite properly..
