### ISSUE TITLE
Allow for editable tags when using multi-select component

### ISSUE THREAD

**Issue by jjstrat3** [furqanZafar/react-selectize#14]
First of all, I wanted to say this is a great library!  I really like what you're doing with it, and the motivations that seemed to go into making it.
That being said, there's one feature I'd like to see that would really cement this library as being in a class of its own compared to other similar tagged-input or multi-select input React component libraries.  Having the ability to have editable values/tags in your multi-select component like you do in the simple, single-select one would be fantastic, and is really the only thing that keeps me from being able to use this library on a project I'm currently building for my work.
While I hate being the guy that just requests features without contributing with a PR,  I don't presently have the time/freedom to work on adding such a feature.  If it's something that you can't get to yourself right away, I understand.  I'll try to find the time to put together a PR in the near future, I just wanted to bring it to your attention.

Thanks again for your work!

**Comment by furqanZafar** [comment]
Thanks for the kind words. MultiSelect does however support `restoreOnBackspace` prop, that updates the search field with the selected value (when you press the backspace key) 
```
<MultiSelect restoreOnBackspace = {function(item){ return item.label }}/>
```

**Comment by gigablah** [comment]
If I add the `restoreOnBackspace` prop to the "Tags" MultiSelect example on the demo site, it apparently interferes with `renderNoResultsFound`. The message "No results found" always displays instead of "Type a few characters to create a tag" or "Tag already exists".

**Comment by furqanZafar** [comment]
Thanks for spotting this :+1:  (silly bug) patch coming up

**Comment by furqanZafar** [comment]
fixed in v0.3.8 updated the example as well http://furqanzafar.github.io/react-selectize/#/?category=multi&example=tags

**Comment by gigablah** [comment]
Awesome :+1:  !!

I also `trim()`ed the `search` parameter so that you cannot create a new item by just adding spaces to an existing one. Putting it here just in case.


```
            // createFromSearch :: [Item] -> [Item] -> String -> Item?
            createFromSearch = {function(options, values, search){
                if (search.length == 0 || 
                    values.map(function(value){ return value.label; }).indexOf(search.trim()) != -1) 
                    return null;
                return {label: search, value: search};
            }}
            
            // renderNoResultsFound :: [Item] -> String -> ReactElement
            renderNoResultsFound = {function(values, search) {
                return <div className = "no-results-found">
                    {(function(){
                        if (search.length == 0)
                            return "Type a few characters to create a tag";
                        else if (values.map(function(value){ return value.label; }).indexOf(search.trim()) != -1)
                            return "Tag already exists";
                    })()}
                </div>
            }}
```

**Comment by furqanZafar** [comment]
Thanks incorporated in examples (http://furqanzafar.github.io/react-selectize/#/?category=multi&example=tags)
