### ISSUE TITLE
defaultValue takes only on mounting

### ISSUE THREAD

**Issue by bibimij** [furqanZafar/react-selectize#146]
SimpleSelect component wrapped with container. Container makes an API call in componentWillMount callback and places it to the redux store. MyComponent looks like this:
```jsx
class MyComponent extends Component {
  render() {
    return (
      <Container>
        <SimpleSelect
          ref="select"
          options={this.state.city}
          search={this.state.search}
          defaultValue={this.props.city}
        />
      </Container>
    );
  }
}

const mapStateToProps = ({city}) => ({
  city: city || ''
});

export default connect(mapStateToProps)(MyComponent);
```

So, on mounting state city is not set. It appears only after API response and rerendering of MyComponent. This is behaviour is actual also for MultiSelect. How to cook it well?

**Comment by countravioli** [comment]
You want to use "value" not "defaultValue." Default value is only used during initialization if you want to change the default to something other than the first option in the options array.

**Comment by bibimij** [comment]
Yes. My bad. I've just change the rendering flow of parent component yesterday. It worked fine now.
