### ISSUE TITLE
Can't dropdown-click options in a plain multiselect

### ISSUE THREAD

**Issue by HoneyryderChuck** [furqanZafar/react-selectize#147]
I'm setting up on of the vanilla examples in my app (no add ons yet), and clicking the arrow for dropdown just won't work. I'm looking at the markup, I don't see the options anywhere (at least no DOM element visible over there). Is it a library bug or a deps issue?

My example:

```javascript
import { ReactSelectize, SimpleSelect, MultiSelect } from 'react-selectize'
import 'react-selectize/themes/index.css'

const Form = () => {
		let options =  [
      "china",
      "korea",
      "japan",
      "nigeria",
      "congo",
      "zimbabwe",
      "germany",
      "poland",
      "spain"].map(function(c) { return { label: c, value: c } })

		return (<MultiSelect
			placeholder="Select a country"
			options={options} onOpenChange={function() {console.log("balls")}} />)
}

ReactDOM.render(
	<Form />,
	root
)
```

Im using react 15.4.2 and react-selectize 2.1.0 (webpack 2), can't think of any other relevant dependency that might be in the middle. Give me a heads up if you need more input.

**Comment by i94u** [comment]
I think you use the wrong props in the <MultiSelect>, you can replace the onOpenChange to the onValuesChange. You can fine the example code in the http://furqanzafar.github.io/react-selectize/#/, the part of "Multi/On values change", hope this info can help you.

**Comment by HoneyryderChuck** [comment]
I did try to use it as it was defined in the example, isolated it and ultimately gave up and replaced it with react-tagsinput with autosuggest , which has been working for now. I'll close this, as I can't reproduce it anymore.
