### ISSUE TITLE
Question: Remove element from the multi select with mouse click

### ISSUE THREAD

**Issue by couds** [furqanZafar/react-selectize#16]
there is a way to remove a element from the selected values with a mouse event (like adding a "x" at the end of each item selected)  or have a onValueSelected event that recieve a function (value,callback) => { .... callback() } 

Thanks

**Comment by furqanZafar** [comment]
Yes, you need to implement the renderValue prop (view this example: http://furqanzafar.github.io/react-selectize/#/?category=multi&example=custom-filtering-and-rendering)
```
// renderValue :: Int -> Item -> ReactElement
renderValue = {function(item){
    return <div className = "removable-emoji">
        <span onClick = {function(){
            self.setState({
                selectedEmojis: _.reject(self.state.selectedEmojis, function(emoji){
                    return emoji.value == item.value;
                }) 
            });
        }}>x</span>
        <img src = {item.value} style = {{marginRight: 4, verticalAlign: "middle", width: 24}}/>
    </div>
}}
```

**Comment by couds** [comment]
Yes I just saw that in the examples. Thanks for your quick answer =)

**Comment by nikkipurcell** [comment]
Does anyone know how to implement this correctly with the advanced tags option? I've added the renderValue above and it works, but the search item typed in remains in the input and only clears if you click outside of the input.

**Comment by nikkipurcell** [comment]
Wow never mind...found the answer by using uid function. (I should have been more careful in reading the documentation)!
