### ISSUE TITLE
Enter keydown event for no matched items

### ISSUE THREAD

**Issue by jamesjjk** [furqanZafar/react-selectize#19]
Hi @furqanZafar ,

I'm using the react-selectize component for a search component to which its very well suited, however in a search it is expected that the enterkeydown or a search event can take place even if no value is selected from the list.. i.e. using a search term. Any tips on the best way to implement this? I noticed the keydown event for "enter" when a value is highlighted from the list. It would be great to be able to enter just on the supplied searchterm.

Many thanks in advance.

**Comment by furqanZafar** [comment]
added an on-enter prop that is fired with the highlighted option (or undefined otherwise) whenever the user hits the enter key:
```
...
onEnter = {(highlightedOption) => {
    if (typeof highlgihtedOption == "undefined") {
        alert("you did not select any item");
    }
}}
...
```
http://furqanzafar.github.io/react-selectize/#/?category=simple&example=event-listeners

**Comment by jamesjjk** [comment]
@furqanZafar Thank you we really appreciate this!

**Comment by furqanZafar** [comment]
`on-enter` prop has been replaced with `on-keyboard-selection-failed` in `0.6.0`
