### ISSUE TITLE
[Feature request] [Multiselect] Add the possibility to confirm a tag with the comma key.

### ISSUE THREAD

**Issue by yuters** [furqanZafar/react-selectize#21]
I have an autocomplete for adding tags, and user tests shows that many users try to confirm their choice and add more tags with the comma key (,).

Is this something you might want to consider adding?

Thanks :)

**Comment by furqanZafar** [comment]
v0.4.0 now supports 2 new props `delimiters` & `valuesFromPaste` that will help you get the desired result.

the delimiters props takes an array of keycodes that will trigger selection of the highlighted item in your case this will be `delimiters = {[188]}` (188 is the keycode for comma)

also you can use the `valuesFromPaste` prop to convert a pasted comma separated string into tags ("Tags - Advance usage"  example: http://furqanzafar.github.io/react-selectize/#/?category=multi&example=tags)

**Comment by yuters** [comment]
You. are. awesome! And the values from paste is a really useful addition.

Thanks a lot, it works great.
