### ISSUE TITLE
Menu list is not shown in a scrollable div

### ISSUE THREAD

**Issue by xabikos** [furqanZafar/react-selectize#22]
Thank you very much for this amazing component. I really want to use it but I face a problem when trying to add the component inside a div that has overflow auto and there is not enough space for the menu to appear. In this case we need to scroll to be able to see all the options. You can see an example here 
![react-selectize](https://cloud.githubusercontent.com/assets/487416/12476472/cb93456c-c029-11e5-80ef-27d525daef29.png)

Instead a behavior like on that follows would be better

![date](https://cloud.githubusercontent.com/assets/487416/11473104/e674d3aa-9770-11e5-8c15-d7c093cafe0a.png)

The second is react-datepicker component and they use [tether library](https://github.com/HubSpot/tether) to achieve that result

**Comment by furqanZafar** [comment]
Thanks for pointing this out, i encountered a similar issue at work, will look into the tether library and see if i can fix it

**Comment by furqanZafar** [comment]
added [tether](http://furqanzafar.github.io/react-selectize/#/?category=multi&example=tether) support in release `0.5.0`, to enable tether simple set `tether` prop to true (tethering is disabled by default, as it is slightly more performance intensive and not required for most use cases)

**Comment by xabikos** [comment]
Awesome! That was what I really needed. Thank you very much for the such a quick addition of the feature!
