### ISSUE TITLE
Feature request: blur method

### ISSUE THREAD

**Issue by jamesjjk** [furqanZafar/react-selectize#24]
@furqanZafar Hey there, thanks again for putting the onEnter event in, it has really helped us a lot. I wondered if it is possible to expose a blur method, so that we can close the drop onEnter when submitting search?

thanks again.

**Comment by furqanZafar** [comment]
onBlur is there already https://github.com/furqanZafar/react-selectize/blob/develop/API.md

**Comment by jamesjjk** [comment]
@furqanZafar yes the event exists. However to forceably close the dropdown. A blur method for the simple select?

**Comment by furqanZafar** [comment]
Added blur method in release `0.5.0`, also pressing return/enter key on an empty dropdown will close it (by default) 

The release has some breaking CSS changes so do check the [changelog](https://github.com/furqanZafar/react-selectize/blob/develop/CHANGELOG.md)
