### ISSUE TITLE
Question: values on the props instead of state

### ISSUE THREAD

**Issue by couds** [furqanZafar/react-selectize#27]
How to manage the callback in the onValueChange whente the values came from the props instead of the state?

in the documentation you put to call the callback like this.setState({...},callback) but what happen when the values are passed via props E.X

you have a high order component that manage the values and on change you change the state of the high order component and this pass down the new values, I tries with a timeout, with the componentWillReceiveProps and nothing work :(

**Comment by furqanZafar** [comment]
a code snippet would help, for HOC you only need to invoke callback(); the problem might be in the way you set the values prop

**Comment by furqanZafar** [comment]
callback from on*Change listeners has been removed in 0.6.0
