### ISSUE TITLE
multiselect doesn't support autoFocus

### ISSUE THREAD

**Issue by thanhvuong** [furqanZafar/react-selectize#28]
Multiselect doesn't seem to support the autoFocus property. Haven't tested with simpleselect but might want to check that out.

**Comment by furqanZafar** [comment]
you can do that in the parent component's `componentDidMount` lifecycle method, like this:
```
componentDidMount: function(){
    this.refs.selectizeInstance.foucs();
}
```

**Comment by furqanZafar** [comment]
added `autofocus` prop in 0.6.0
