### ISSUE TITLE
Placeholder overflows in IE and Firefox

### ISSUE THREAD

**Issue by xabikos** [furqanZafar/react-selectize#29]
When the placeholder is long it overflows in all browsers except chorme and look like the following image 

![selectize](https://cloud.githubusercontent.com/assets/487416/12674032/d52e52ee-c680-11e5-91b2-30a4564280a5.png)

This is caused because the [corresponding style](https://github.com/furqanZafar/react-selectize/blob/c2437b7e739c0cd53f887a2dd5ed235e44d9ad08/src/ReactSelectize.styl) that calculates the max width has a vendor prefix. I guess is safe enough to just remove the webkit prefix.

**Comment by furqanZafar** [comment]
Thanks for pointing this, will publish a release to npm with some other fixes soon.

**Comment by furqanZafar** [comment]
fixed in 0.6.0

**Comment by xabikos** [comment]
Thanks a lot!
