### ISSUE TITLE
IE9 & IE10 input width behavior

### ISSUE THREAD

**Issue by ziazek** [furqanZafar/react-selectize#3]
![screenshot 2015-10-10 15 30 42](https://cloud.githubusercontent.com/assets/505254/10410513/e469d754-6f75-11e5-806e-321aacd16e67.png)
![screenshot 2015-10-10 15 30 52](https://cloud.githubusercontent.com/assets/505254/10410512/e4679f70-6f75-11e5-9c0e-2fec18498aa1.png)
![screenshot 2015-10-10 15 31 10](https://cloud.githubusercontent.com/assets/505254/10410511/e462b3d4-6f75-11e5-91a2-53750b3efb12.png)

The SimpleSelect box in IE9 and IE10 had the above issue. Inspecting the element showed that the width of the input was very large (over 1000px). using `autosize` with

```
function($search){return $search.value.length * 10}
```

solved the issue. I thought i'd submit an issue because it was unexpected.

Thanks for your work on this component, it's very useful. Cheers.

**Comment by furqanZafar** [comment]
Thanks for pointing it out, will look into this.

**Comment by mauriyouth** [comment]
same with firefox 38

**Comment by furqanZafar** [comment]
I am unable to reproduce this issue, I have tried with IE 9 / 10 & now Firefox 38. 
I tried the examples page in both the browsers, which uses v0.3.4.

**Comment by furqanZafar** [comment]
Finally able to reproduce the issue in FF 38, v0.3.5 should solve it.

**Comment by mauriyouth** [comment]
well done :+1:

**Comment by furqanZafar** [comment]
cheers
