### ISSUE TITLE
Feature request: Mix options with option group and options without option group

### ISSUE THREAD

**Issue by marchbnr** [furqanZafar/react-selectize#30]
It should be possible mix options with groups and options without group.

Right now, it is only possible to have all options with or without groups, but not both.

I suggest, that groups with an undefined label are handled like ordinary options without group. The order of the options may remain the same (ordered by group), however it would be more flexible if options would not be reordered by their group in that case. Changing the order might also be another feature, though.

**Comment by furqanZafar** [comment]
The group title is simply a display, you can achieve your goal by doing this (paste it directly in the options group example (jsx editor)):
```
renderGroupTitle = {function(index, group){
    if (typeof group.title == "undefined") {
        return null
    } else {
        return <div className= "simple-group-title">{group.title}</div>
    }
}}
```
this will keep the ordering, simply remove the group title (the end result is the same)

**Comment by marchbnr** [comment]
Thanks for the quick reply (as always :+1: ). Will look into it.

**Comment by marchbnr** [comment]
Okay it works.

However, I would suggest to change the implementation of renderGroupTitle to return null if the title is null. Changing the implementation creates a coupling, that breaks if the implementation, for example the class name of the div, is changed.
