### ISSUE TITLE
Question: Is it possible to open the react-selectize dropdown from code?

### ISSUE THREAD

**Issue by tfan** [furqanZafar/react-selectize#32]
Hello, I'm still a bit new to React and I apologise if I might have misunderstood something in the documentation. 

I am trying to make an autocompleter for addresses using react-selectize and I was wondering if there is any way I can open the dropdown programmatically? The service I'm using firstly returns street names, then actual addresses once you have chosen a street name.

I've tried defining the "open" property (referencing a boolean) but my dropdown seems to get stuck when I try, so before I start debugging and eventually pasting code (sorry), I wanted to ask if it is me doing it all wrong?

Thanks,
Thomas

**Comment by furqanZafar** [comment]
you can do it by using the `open` prop like this (you can test the following by pasting it in the jsx editor in the [examples page](http://furqanzafar.github.io/react-selectize/#/?category=simple)):
```
// SimpleSelect = require("react-selectize").SimpleSelect

Form = React.createClass({
    
    // render :: a -> ReactElement
    render: function(){
        var self = this, 
            options = ["apple", "mango", "grapes", "melon", "strawberry"].map(function(fruit){
                return {label: fruit, value: fruit}
            });
        return <div>
            
            <SimpleSelect 
                options = {options} 
                placeholder = "Select a fruit"
                open = {this.state.open}
                onOpenChange = {function(open){
                    self.setState({open: open})
                }}
            />
            
            <button onClick = {function(){
                self.setState({open: true})
            }}>Open me</button>
        
        </div>
    },
    
    getInitialState: function(){
        return {open: false}
    }
    
});

render(<Form/>, mountNode)
```

**Comment by tfan** [comment]
Thank you so much!
