### ISSUE TITLE
TypeScript type definition files

### ISSUE THREAD

**Issue by caguthrie** [furqanZafar/react-selectize#34]
Do any TypeScript definition files exist for this or are there plans for any?

**Comment by furqanZafar** [comment]
Currently there are no TypeScript definition files. PR's welcome

**Comment by vintem** [comment]
I can do that. I did the typings for my project, I can polish them and make a PR.

**Comment by vintem** [comment]
Should I make the PR on develop or on master?

**Comment by furqanZafar** [comment]
Develop. Thanks for the PR :+1:

**Comment by ehartford** [comment]
this still isn't in master.
PR https://github.com/furqanZafar/react-selectize/pull/135
