### ISSUE TITLE
IE 11 and flexbox

### ISSUE THREAD

**Issue by xabikos** [furqanZafar/react-selectize#35]
I am in the latest version (0.7.2) and I have an issue with the drop down symbol (caret) and clear button (x). More specifically they are not vertically aligned as you can see in the following image
![ieflexbox](https://cloud.githubusercontent.com/assets/487416/12949899/ac26c6cc-d00a-11e5-9c37-f54f95d6a772.png)

I have an example with and without a selected value. I see that the component uses the flexbox model and I don't know if it's related to [this issue](https://connect.microsoft.com/IE/feedback/details/816293/ie11-flexbox-with-min-height-not-vertically-aligning-with-align-items-center). In Chrome and Firefox works fine.

**Comment by furqanZafar** [comment]
fixed in release 0.7.4, just used `height` for reset & arrow containers instead of `min-height` 
Thanks

**Comment by xabikos** [comment]
Yes it's fixed. Thank you very much for such an immediate response once again.
