### ISSUE TITLE
Cannot drag the dropdown scrollbar in IE11

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#36]
When the dropdown is a long list, the scrollbar appears.
However, in IE11, whenever you try to use your mouse to drag the scrollbar to scroll down, it immediately close the dropdown. 
The same thing doesn't happen on Chrome though.
I think IE handles focus differently than Chrome, and it breaks the scrollbar in IE.
Still haven't got chance to debug further, but i think this is quite annoying for users on IE since you can't scroll using mouse anymore.

**Comment by furqanZafar** [comment]
Which version of selectize are you using? try version 0.7.4

**Comment by cheahkhing** [comment]
@furqanZafar You're right, the latest version doesn't have this issue anymore. Seems to be fixed.
Thanks.

**Comment by natenorberg** [comment]
Did something break this again? I'm still seeing this in IE11 in windows 7 with version 3.0.1

I can't reproduce it in windows 8.1 though
