### ISSUE TITLE
Focus is not working properly in IE11 after reset & arrow is changed to svg

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#37]
Basically with the latest 0.7.4 version, reset & arrow have been changed to SVG element. And this actually causes IE11 to capture the focus on them when you press "tab".
So, previously you just need to press "tab" once to move from 1 selectize control to the next one, now you'll need to tab once/twice more depending you have value set or not. (With value set, the reset svg is visible, so focus moved there first, then followed by arrow svg).
I tried to workaround it by adding "focusable: 'false'" attribute to svg, but seems like this attribute is not supported yet by reactjs. :(   stuck now. any idea?

**Comment by furqanZafar** [comment]
will look into it, thanks for pointing it out

**Comment by furqanZafar** [comment]
should be fixed in 0.8.0
