### ISSUE TITLE
Default Value support for SimpleSelect

### ISSUE THREAD

**Issue by mauriyouth** [furqanZafar/react-selectize#4]
Hello,
is defaultValue supported for SimpleSelect? because the attribute 'value' makes it impossible to change the value.
`<SimpleSelect
defaultValue={...} >`

**Comment by furqanZafar** [comment]
Good point about defaultValue. (will look into it) 

the value attribute works like that of React.DOM.Select, so you need you update the value you provide when it changes, like this:
```
...
render: function(){
    var self = this;
    return <SimpleSelect
        value = {this.state.selectedValue}
        onValueChange = {function(newValue, callback){
            self.setState({selectedValue: newValue}, callback);
        }}
    />
}

getInitialState: function(){

    // this is your initial value
    return {
        selectedValue: {
            label: "a",
            value: "a"
        }
    }

}
...
```

**Comment by furqanZafar** [comment]
added `defaultValue` prop for SimpleSelect & `defaultValues` prop for MultiSelect, in release 0.3.1

**Comment by mauriyouth** [comment]
:) :+1:

**Comment by mauriyouth** [comment]
your last push did induce erros, search is not working anymore

**Comment by furqanZafar** [comment]
yea version 3.0.x only works with React 0.14.0

**Comment by mewben** [comment]
Is it possible to just supply the `value` in the `defaultValue` instead of supplying the entire option `label, value`?

**Comment by furqanZafar** [comment]
No. 

This is the intended behaviour, just supplying the value to the `default-prop` makes it difficult to reason about the component (especially when working with custom Items), introduces extra type checks & makes the component more error prone.

The type of the defaultValue prop is `Item`which means you have to supply the complete object. 
by default, `Item` is a type alias for `{label :: String, value :: a}` where value can be of any type.

This is consistent throughout the component, all the props and event listeners share the same type.
`defaultValue :: Item`, `value :: Item`, `onValueChange :: Item -> (() -> Void)` etc.

**Comment by mnieber** [comment]
The proposed solution didn't play nicely for me when used together with `createFromSearch`. Since the new option is not one of the standard available options, entering the name of the new option caused the selector to become empty. I came up with this alternative (still, I would welcome a `defaultValue` attribute):

    export default class MySelector extends React.Component {

      constructor(props) {
        super(props);
        this.state = {
          selectorOption: null
        };
      }

      _getDefaultOption = () => {
        return this.state.selectorOption !== null
          ? this.state.selectorOption
          : this._options().find(
              o => o.value === this.props.defaultValue
            );
      }

      _options = () => {
        return [
          {label: "one", value: 1}
          {label: "two", value: 2}
          {label: "three", value: 3}
        ]
      }

      render() {
        return <SimpleSelect
          value={this._getDefaultOption()}
          onValueChange = {option => {
            this.setState({
              selectorOption: option
            });
          }}      
          options={this._options()}
        >
        </SimpleSelect>
      }
    }
