### ISSUE TITLE
Enable options for press "tab" to select capability

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#42]
Hi, in selectize, there is an option for us to use "tab" key for selection instead of the usual "enter" key.
Do you think we can make this as an option for react-selectize as well?
Or is there any way for me to customize this?

**Comment by furqanZafar** [comment]
you can use `delimiters: [9]`

**Comment by cheahkhing** [comment]
I tested your suggestions, it works partially. Now it will selects the option when I press "tab" key, but it doesn't continue to move the focus forward. I actually need it to behave like "tab" to select and then move on to the next control. Not sure if this behaviour can be customized?

**Comment by furqanZafar** [comment]
Hmm, you can update the focus manually using `onValueChange`, will see if I can get it to work out of the box

**Comment by cheahkhing** [comment]
Hi, do you mind to tell me how can i update the focus onValueChange? for now maybe i'll just do it manually while waiting for you enhancement. :)

**Comment by furqanZafar** [comment]
something like this should work:
```onValueChange: {function(){
    self.refs.nextInputElement.focus();
}}```  (http://furqanzafar.github.io/react-selectize/#/?category=simple&example=event-listeners)

**Comment by cheahkhing** [comment]
Hi, your suggestion doesn't work for my case because I won't know what would be my next element. The whole form is generated dynamically. So, i won't be able to hard-code what's the next element and use it to focus(). Was looking for ways to send "tab" keystroke, so that no matter which element you're on, it will just simply move the focus to the next element.

**Comment by furqanZafar** [comment]
I have added a new prop `cancelKeyboardEventOnSelection` in release 0.8.1 
here is a demo: http://codepen.io/furqanZafar/pen/eJaKwX

**Comment by cheahkhing** [comment]
@furqanZafar This is really nice! Works exactly what I need. Really appreciate your quick support!

**Comment by furqanZafar** [comment]
np
