### ISSUE TITLE
Not able to select text of selected value

### ISSUE THREAD

**Issue by babak49** [furqanZafar/react-selectize#47]
I not able to select text of value using the mouse even on example page, but I can select text using keyboard.
If I add to my component open={true}  and editable={true} (I know that it will throw a warning to the console) text selecting will work. But this is not the best case when your dropdown is always opened.

**Comment by QuietOmen** [comment]
I can confirm this issue, and I haven't been able to find an alternative work-around to fixing it than what was posted above.

**Comment by furqanZafar** [comment]
Tricky issue:
The moment you click anywhere on the select control (**including** the search field), it blurs the focus from the search field causing the dropdown to close. 
To prevent this behaviour I cancel the mousedown event on the select control, but this also prevents selection of text. 

Release 0.8.3, tries to solve this issue to some extent, by cancelling the mousedown event on the control alone (**excluding** the search field), you will still have to use `editable: ({label}) => label` though.

**Comment by babak49** [comment]
Yes release 0.8.3 solve this issue. Thank you!
