### ISSUE TITLE
Parameterize parent node when tether=true

### ISSUE THREAD

**Issue by karleberts** [furqanZafar/react-selectize#49]
When using the `tether` prop, the dropdown is appended to `document.body`.  It would be nice if I could pass a node to append to instead.  In my particular case, I need to avoid triggering a mouseout when I hover the dropdown.

**Comment by furqanZafar** [comment]
A code pen / snippet would be helpful, I am not sure if tether library has an option for this.

**Comment by furqanZafar** [comment]
added a `tetherProp` prop in release 0.8.4 that allows you to set the parent element like this:
`tetherProp = {{parentElement: () => document.getElementById("my-element-of-interest")}}`
