### ISSUE TITLE
dropdownDirection doesn't work

### ISSUE THREAD

**Issue by zdila** [furqanZafar/react-selectize#50]
Not sure why, but `dropdownDirection` works only if I specify `px` in `DropdownMenu.js`. Using react 0.14.7.

`< return (this.props.bottomAnchor().offsetHeight + dropdownMenu.style.marginBottom);`
`> return (this.props.bottomAnchor().offsetHeight + dropdownMenu.style.marginBottom) + 'px';`

**Comment by cheahkhing** [comment]
In fact, i can't get it work either. :(

**Comment by furqanZafar** [comment]
should be fixed in release 0.9.0
