### ISSUE TITLE
Enable tooltips on Delete button

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#51]
Just a small enhancement on the "X" button: it would be nice to have a tooltips showing "Delete All" / "Clear All" / "Reset". I thought a simple "title" attribute would work, but i think because it is a SVG element, title is being ignored. So, maybe need a way to add the title in so that by default browsers will render a small tooltips when hovering over the "X" button.

**Comment by furqanZafar** [comment]
you can customise the reset button using `renderResetButton` props, like this:
```javascript
renderResetButton = {() => {
    return <span title="Reset">x</span>
}}
```

**Comment by cheahkhing** [comment]
Arh, i miss this one, i think it should work then. :) thanks.
