### ISSUE TITLE
How to trigger "onHighlight" event for options?

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#56]
Hi, i know that we can customize the rendering of options.
But when user is using keyboard "up / down" arrow to highlight the options, how can i get the events?
I need the events to be triggered when an option is being highlighted. Is this supported?

**Comment by furqanZafar** [comment]
added in release 0.9.0, example:
http://codepen.io/furqanZafar/pen/qZRGrX

**Comment by cheahkhing** [comment]
nice enhancement, this one works perfectly for me now. :) thanks.
