### ISSUE TITLE
Enable onPaste / valueFromPaste as well for SimpleSelect

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#57]
Currently only MultiSelect has the valuesFromPaste method, for SimpleSelect, it would be nice to have as well, since ReactSelectize already capturing the keystroke of "Paste", i think enable OnPaste as well on SimpleSelect would be good for us to customize the what to do with the value pasted.

**Comment by furqanZafar** [comment]
added in release 0.9.0, example:
http://codepen.io/furqanZafar/pen/BKpezv

**Comment by cheahkhing** [comment]
awesome support! :) works greatly now.
