### ISSUE TITLE
Not selecting on `enter` keypress

### ISSUE THREAD

**Issue by tgoldenberg** [furqanZafar/react-selectize#58]
We are currently using `"react-selectize": "^0.5.0",`, and the `SimpleSelect`. I am having an issue selecting the option with the `enter` keypress. It does nothing, not able to trace any callback or anything. Yet, it works fine with `MultiSelect`. Why is this? Any help would be appreciated :)

**Comment by tgoldenberg** [comment]
Ending up implementing something like this: 

`onEnter={(item) => {
                    console.log('HIGHLIGHTED', item);
                    this.setState({
                      items: [item].concat(this.state.items),
                      search: '',
                    })
                    this.refs.select.blur();
                  }}`

**Comment by modestguy** [comment]
@tgoldenberg and what about Esc key? how to prevent "valueChange event" when "esc" button pressed?
