### ISSUE TITLE
animated dropdown(transitionEnter, transitionLeave) not working

### ISSUE THREAD

**Issue by seoyoochan** [furqanZafar/react-selectize#59]
I followed the example JSX code from the animated dropdown.
if I pass `transitionEnter`, `transitionLeave` to true for `<MultiSelect>`, the dropdown does not display because of the height set to 0px on the dom.

when those are false, it works without animation.

**Comment by furqanZafar** [comment]
unable to reproduce, here is a pen illustrating animation for MultiSelect (using version 0.9.0) with `default` theme
http://codepen.io/furqanZafar/pen/aNJdmg

**Comment by seoyoochan** [comment]
@furqanZafar do i need to install and require any other packages? I am using React, Webpack, ES6 jsx.

**Comment by cheahkhing** [comment]
@seoyoochan can you explain a little bit more why it doesn't work with the animation? i also seeing some issues when i turn on animation. mine 1 simply throwing exceptions on react.
React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `DropdownMenu`.
i thought it is just my integration issue. maybe i can get some ideas from you.

**Comment by furqanZafar** [comment]
a codepen / jsfiddle would help, I am unable to reproduce these issues with animation. Do you have similar issues with the example here (http://furqanzafar.github.io/react-selectize/#/?category=multi&example=animated-dropdown) or the codepen I posted earlier?

**Comment by seoyoochan** [comment]
@cheahkhing I think you exported React component incorrectly. that's usually happens when export was not correct. 

@furqanZafar http://codepen.io/seoyoochan/pen/VaWLwj#0

**Comment by furqanZafar** [comment]
@seoyoochan  here is the fixed pen (with a working animated dropdown) http://codepen.io/furqanZafar/pen/GZEJqv)

These are my changes:
* use react-with-addons: `https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-with-addons.min.js`
* removed SASS preprocessor (you can also use the CSS file available on CDN `https://npmcdn.com/react-selectize@0.9.0/dist/index.min.css`)
* removed unwanted import statements

**Comment by seoyoochan** [comment]
@furqanZafar thanks, maybe I am missing to install some dependencies? :confused:
