### ISSUE TITLE
Can't setState after initial selection

### ISSUE THREAD

**Issue by jarsbe** [furqanZafar/react-selectize#6]
I have setState attached to a couple of form elements which work fine, once I use the SimpleSelect those setState handlers brake. They work fine without selectize.

```
constructor(props) {
  super(props)

  this.state = {
    writable: false
  }
}

handleCheckboxChange(e) {
  this.setState({
    writable: !this.state.writable
  })
}

render() {
  return (
    <div className='body'>
      <SimpleSelect options={this.props.options}
                    placeholder='Select a field' />

      <input type='checkbox'
             checked={this.state.writable}
             onChange={(e) => { this.handleCheckboxChange(e) }} />
    </div>
  )
}
```

`handleCheckboxChange` will work correctly until I make a selection with the SimpleSelect. The select works but `handleCheckboxChange` will never call. I'm using React 0.14.0. Let me know if you need more details or a repo.

**Comment by furqanZafar** [comment]
Thanks for spotting that, patch coming up.

**Comment by furqanZafar** [comment]
The bug was introduced in release 0.3.2, the dropdown-transition element blocked the DOM elements underneath, your code should work fine with 0.3.4.

**Comment by jarsbe** [comment]
Wow that was quick! Really appreciate that and nice module - stateless components for the win :smile: Will upgrade tomorrow morning and hopefully close this issue.

**Comment by furqanZafar** [comment]
:+1:  caught my eye at the right time, will post more details, somewhere, on how the "stateless" bit of it works.

**Comment by jarsbe** [comment]
Success! I'd love an article on the statelessness. More 3rd party components should take this same approach.
