### ISSUE TITLE
ResizableInput doesn't respect parent container width

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#62]
For both SimpleSelect & MultiSelect, user might pasted in a long text / type a very long text.
The issue here is that the input will keep growing without respecting the parent container, causing the text to be overlapping other elements.

**Comment by KirilYDimitrov** [comment]
![input](https://cloud.githubusercontent.com/assets/19471887/15394539/2bd147ca-1ddc-11e6-9d75-8d3b2c8a549d.png)
I found the same issue. Can you provide a solution asap. Thanks in advance.

**Comment by furqanZafar** [comment]
Duplicate see #75 for solution
