### ISSUE TITLE
RenderValue is not being triggered on parent render() cycle

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#63]
I believe this is due to the way ReactSelectize implement shouldComponentUpdate().
In my usage, even though the selectedValues didn't change, but i still want to update the selectedValues rendering due to my parent state changes. How can i tell ReactSelectize to force update the values in this case?

**Comment by furqanZafar** [comment]
you can use the `uid` prop for this purpose, for example:

```
x = 1
uid: (item) =>
 {value: item.value, x}
```

**Comment by avivalk** [comment]
I'm having a similar issue as well, where I want to force refresh the ReactSelectize so it displays the placeholder instead of the previously selectedValue.  How can I force refresh the component?

**Comment by furqanZafar** [comment]
@avivalk seems to be unrelated, if you want to show the place-holder you will need to reset the `value` or the `values` prop, something like:
```javascript
...
value = {this.state.selectedValue}
onClick = {() => {
 this.setState({selectedValue: undefined})
}}
```

**Comment by avivalk** [comment]
@furqanZafar sorry if this maybe belongs in a different issue, but I'm setting something else in the parent state and the options list is getting updated but the previously selectedValue remains.  I want a fresh dropdown with the placeholder when the options list gets updated

**Comment by furqanZafar** [comment]
@avivalk 
you can take advantage of the `controlled` nature of `selectize` (as I mentioned earlier), checkout this pen (http://codepen.io/furqanZafar/pen/ONOZzG), it does what you have described

**Comment by avivalk** [comment]
@furqanZafar that pen works when the button is within the _same_ component as the `selectize`. My issue is that the reset action happens in the parent component and I can't change the state within the `selectize` component.

**Comment by furqanZafar** [comment]
@avivalk you can do that as well by checking if the selectedItem is in the list of options or not, something like this:
```javascript
    const selectedItem = this.props.options.find(({value}) => { 
      return this.state.selectedItem && value == this.state.selectedItem.value
    })
    
    return <div>
      <reactSelectize.SimpleSelect 
          placeholder = "Select an item"
          value = {selectedItem}
          onValueChange = {(item) => this.setState({selectedItem: item})}
          options = {this.props.options}
      />      
    </div>
```
http://codepen.io/furqanZafar/pen/ONOZzG

**Comment by avivalk** [comment]
@furqanZafar I see thanks
