### ISSUE TITLE
Default to create search

### ISSUE THREAD

**Issue by tgoldenberg** [furqanZafar/react-selectize#67]
I am using `"react-selectize": "^0.5.0",` and I want the options dropdown to highlight the create search value if there is one unless the user specifies otherwise. I noticed that there is a default to first option in later versions of the package but I want to stay in this version (I have had several bad experiences upgrading). Any suggestions on how I can implement this with this version of the package? Thank you, the help is appreciated!

**Comment by furqanZafar** [comment]
you want to highlight the new option as the user types in the search field? or you want to highlight an option in the dropdown menu that has been created by the user (after he selects "Add xyz ...")? please elaborate.

> I have had several bad experiences upgrading
what bad experiences did you have while upgrading?

**Comment by tgoldenberg** [comment]
Hi @furqanZafar, I want the new option to highlight whenever the user types in the search field. Currently, the first option is being bypassed by the highlighter and it is highlighting the closes match in the options. For example, the user types in `face`. The dropdown shows `add face...` but highlights `Facebook` below it. I want it to default to highlighting `add face...` unless the user clicks on a different one or uses the directional keys down or up.

**Comment by tgoldenberg** [comment]
I've tried hackish `jQuery` solutions to no avail. Also, since the code is not written in very understandable ES6, it is hard for me to customize. I wish there was a version that was straightforward and easy to understand for React ES6... i.e. `class MultiSelect extends React.Component{`....

**Comment by tgoldenberg** [comment]
Seriously considering alternatives because of how confuscated the code is. Can there be a version / tag with regular ES6 syntax in addition to the livescript / hard-to-understand js that gets compiled? That would make the package easier to contribute to as well.

**Comment by furqanZafar** [comment]
lol thanks for the feedback, will look into creating an ES6 version, you can get the desired effect in the latest version using:
```javascript
firstOptionIndexToHighlight = {() => 0}
```
sadly, version 0.5.0 doesn't support this

**Comment by tgoldenberg** [comment]
Yeah, when I upgrade to `0.9.0`, everything breaks - the functionality, the styles, everything. I really hope you are able to get an ES6 version of this to make sense of using the package. At this point, definitely not backwards compatible @furqanZafar

**Comment by tgoldenberg** [comment]
I notice that there is a property of `MultiSelect` that is called `firstOptionIndexToHighlight`. Is there any way I can use this to achieve the result?

**Comment by tgoldenberg** [comment]
Please add this snippet to v5.3.0 in `ReactSelectize.js`, under `highlightAndScrollToSelectableOption` --- 
`  if (direction == 0) {
        index = 0;
      }`
