### ISSUE TITLE
styling long text strings

### ISSUE THREAD

**Issue by wiber** [furqanZafar/react-selectize#75]
In this screenshot the selected text is 'pushed up' by the text input line. Any way to keep it on the same line / level / y position?

![image](https://cloud.githubusercontent.com/assets/71066/14935490/658586a4-0ee4-11e6-9052-1f35b05347bf.png)

**Comment by furqanZafar** [comment]
You can do it by setting text-overflow, max-width & overflow styles in your CSS file (for .simple-value class) or via inline styles by providing a custom render function for the selected value:

```js
// SimpleSelect = require("react-selectize").SimpleSelect

Form = React.createClass({
    
    // render :: a -> ReactElement
    render: function(){
        var self = this, 
            options = [
                "the-quick-brown-fox-jumped-over-the-lazy-dog",
                "the quick brown fox jumped over the lazy dog", 
                "mango", 
                "grapes", 
                "melon", 
                "strawberry"
            ].map((fruit) => {
                return {label: fruit, value: fruit}
            });
        return <SimpleSelect 
            options = {options} 
            placeholder = "Select a fruit"

            // :: Item -> ReactElement
            renderValue = {(item) => {
                return (
                    <div style = {{
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                        whiteSpace: "nowrap",
                        maxWidth: 200
                    }}>{item.label}</div>
                )
            }}

        />
    }
    
});

render(<Form/>, mountNode)
```

**Comment by wiber** [comment]
Great! thanks. 

What does wrapping it in {} do to that livescript function? 

I think this does the same thing, at least it seems to work in reactKup:

`renderValue: (item) ->
              that = this
              reactKup (k) ->
                k.div
                  style:
                    overflow: "hidden"
                    textOverflow: "ellipsis"
                    whiteSpace: "nowrap"
                    maxWidth: 200
                  item.label`
