### ISSUE TITLE
No values prop on MultiSelect? Breaks change handler?

### ISSUE THREAD

**Issue by kevzettler** [furqanZafar/react-selectize#84]
I'm trying to setup a `redux-form` wrapper for `react-selectize` see: 
http://redux-form.com/5.2.5/#/faq/custom-component?_k=7m8dyf

So far this is working great for `SimpleSelect` because it offers the `value` prop which I can pass in the dynamic redux-form field value.

It doesn't work with `MultiSelect` as there's no prop for the 'live' value of the input. Looking at the source it appears `MultiSelect` had a `values` prop that looks like it should work but is commented out

http://redux-form.com/5.2.5/#/faq/custom-component?_k=7m8dyf

Could I restore that prop? or is there more to the story?

**Comment by furqanZafar** [comment]
the values prop for MultiSelect is there (just like the value prop for SimpleSelect), it is a controlled prop, here is a codepen illustrating how it can be used (react-selectize@2.0.2):
http://codepen.io/furqanZafar/pen/xOVzBd

Note: the `values` prop expects an array instead of a single item

**Comment by kevzettler** [comment]
Thanks @furqanZafar

**Comment by kevzettler** [comment]
@furqanZafar actually I think there is a bug here. if you check your codepen. You can not select an additional option form the multiselect drop down. Try selecting the `two` or `three` options. This is the same behavior I was seeing. It appears that setting `values` prop breaks the change handler?

**Comment by furqanZafar** [comment]
@kevzettler values prop is a controlled prop as I mentioned earlier, much like the `value` prop of an `<intpu/>` element, i.e. `onValuesChange` you have to update the state of the parent component which in turn would update the `values` prop (illustrated by this pen http://codepen.io/furqanZafar/pen/xOVzBd)
