### ISSUE TITLE
Exposing Current Filtered Options

### ISSUE THREAD

**Issue by cheahkhing** [furqanZafar/react-selectize#85]
Hi,

Is there a way to get currently filtered list of options?

For eg: when user type on the MultiSelect, it filtered the options and shows only 3 options. 
So, I would like to do something with the filtered list when user do some special keystroke, like "Ctrl+T" will select these 3 options automatically.

**Comment by furqanZafar** [comment]
@cheahkhing you can access the filtered options using: `this.refs.select.getComputedState().filteredOptions` here is a CodePen illustrating how you can achieve the desired behaviour using the same http://codepen.io/furqanZafar/pen/xOVzBd

**Comment by cheahkhing** [comment]
Thanks! this works perfectly.
