### ISSUE TITLE
Simple Select input click should always focus

### ISSUE THREAD

**Issue by lomteslie** [furqanZafar/react-selectize#91]
I'm implementing SimpleSelect, and when I click on the input once it focuses. When I click on it again it blurs. I'd expect the normal behavior to always focus the input. 

At the very least it would be helpful to have the `onBlur` event have the type property so I can detect clicks and refocus on the input myself, but that feels real hacky.

**Comment by furqanZafar** [comment]
Hmm, that happens because the input size grows as you type, so initially the size is ~4 px so when you click on the placeholder it registers a click outside the input element which cause the blur event which in turn hides the dropdown

**Comment by lomteslie** [comment]
This is resolved by [this PR](https://github.com/furqanZafar/react-selectize/pull/102)
